name: CommonUtilities
version: ${project.version}
main: it.novaverse.commonutilities.CommonUtilities
authors: [ sgdc3 ]
description: A collection of common commands and features
api-version: '1.21'
softdepend: [ PlaceholderAPI, LuckPerms ]

libraries:
  - "org.incendo:cloud-core:${cloud.version}"
  - "org.incendo:cloud-annotations:${cloud.version}"
  - "org.incendo:cloud-paper:${cloud-paper.version}"
  - "org.incendo:cloud-minecraft-extras:${cloud-minecraft-extras.version}"
  - "io.github.classgraph:classgraph:${classgraph.version}"
