name: CommonUtilities
version: ${project.version}
main: it.feargames.commonutilities.CommonUtilities
authors: [sgdc3]
description: A collection of common commands and features
softdepend: [ProtocolLib]
api-version: '1.13'
